# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # https://github.community/t/solved-workflows-and-git-logs/121289
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-botbay.ml-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-botbay.ml-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: NPM Install
        run: npm install
      # - name: NPM Test
      #   run: npm test
      - name: Build
        run: npm run build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Deploy GitHub Pages
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-botbay.ml-${{ hashFiles('**/package.json', 'jekyll/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-botbay.ml-
    - name: Bundle Cache Config
      run: |
        sudo gem install bundler
        # bundle config path ~/.npm/bundle

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Config Git
      run: |
        git config --global user.name 'Huan @ GitHub Action'
        git config --global user.email 'zixia@zixia.net'
    - name: Create orphan branch for gh-pages
      run: |
        git checkout --orphan gh-pages
        git reset --hard
        git commit --allow-empty -m "Orphan init"
        git checkout main
    - name: Install dependencies
      run: |
        make install
    - name: Bind git worktree with dist/spacle-ng folder and gh-pages branch
      run: |
        rm -fr dist/spacle-ng
        git worktree add dist/spacle-ng gh-pages
    - name: Build and copy all homepage files to dist/spacle-ng/ together
      run: |
        npm run build
    - name: Deploy dist/spacle-ng
      run: |
        pushd dist/spacle-ng
        git add --all
        git commit -m "$(jq -r .version ../../package.json)"
        git push -f origin gh-pages
        popd
    - name: Unbind dist/spacle-ng folder from gh-pages branch
      run: |
        git worktree remove dist/spacle-ng
        git branch -D gh-pages
        rm -fr dist/spacle-ng

